### ISSUE TITLE
sed -i error on macOS Catalina 10.15.3

### ISSUE THREAD

**Issue by dwsmith1983** [tanrax/maza-ad-blocking#1]
`sed: 1: "1i\### Created by Andro ...": extra characters after \ at the end of i command`

I am on macOS Catalina 10.15.3

**Comment by tanrax** [comment]
It seems that OSX is outdated SED. I've created a small update. 

First uninstall it as indicated by the README.

`sudo rm /usr/local/bin/maza && sudo rm ~/.maza`

On OSX install the latest version of SED, with...

`brew install gsed`

Y finally install again

`curl -o maza https://raw.githubusercontent.com/tanrax/maza-ad-blocking/master/maza && chmod +x maza && sudo mv maza /usr/local/bin`

Good luck

**Comment by dwsmith1983** [comment]
brew install gnu-sed
