### ISSUE TITLE
dnsmasq.conf settings

### ISSUE THREAD

**Issue by niladrishekhar** [tanrax/maza-ad-blocking#10]
Hi Apologies for seeking attention by raising an issue. 

I need some help with this -
Edit file in path.

/etc/dnsmasq.conf
Add the following line at the end.

conf-file=(your user path)/.maza/dnsmasq.conf
Example

conf-file=/home/myuser/.maza/dnsmasq.conf

I am using a kali linux with a root user and a kali user so what would be the user path - should it be the path for both root and the kali user ? 

How do I get the path ? also .maza/dnsmasq.conf doesnt exist. I initiated the installation and then got stuck so had to remove it - the rm command for .maza said couldn't as it doesn't exist.

**Comment by tanrax** [comment]
@niladrishekhar  Hello, maybe you run it with `sudo`? In that case it will appear in `/root/.maza/dnsmasq.conf`. Is it there?

**Comment by niladrishekhar** [comment]
Hi - thanks for your prompt response. The query returns 
cat: /root/.maza/dnsmasq.conf: No such file or directory

These are the steps I followed 
1. sudo apt update
2. sudo apt install dnsmasq
3. curl -o maza https://raw.githubusercontent.com/tanrax/maza-ad-blocking/master/maza && chmod +x maza && sudo mv maza /usr/local/bin

Do I need to run something that would generate the .maza file ?

**Comment by tanrax** [comment]
Yes, execute: `maza update`
