### ISSUE TITLE
Question about hosts file and DNSMASQ

### ISSUE THREAD

**Issue by TommieWong** [tanrax/maza-ad-blocking#13]
Hi @tanrax,
Thanks a lot for the code; seems very useful.
Two questions that I cannot find the answer to:
- in the readme, you write: "Unfortunately the hosts file does not support sub-domains (wildcards), which is necessary to correctly filter all DNS." Does this mean that using DNSMASQ and telling my OS to use this local DNS is necessary for maza to work properly? I use a VPN which makes me use its own DNS servers and I am quite happy with that; I would rather not set up something else. Any impact?
- In issue #3 on adding custom rules, you say: "It does not alter the operation of your operating system. To add your addresses, just edit your hosts file." Does this mean that maza does not alter the hosts file? I thought the whole point was to update the hosts file using the StevenBlack list (which is where I read about maza), but it now seems like I am mistaken. Can you explain how this works, then? If it doesn't use the hosts file, then I get I should expunge my existing hosts file of the StevenBlack rules, as these would at some point become obsolete.
Thanks for the feedback!
Tommie

**Comment by tanrax** [comment]
Hello @TommieWong ,
regarding the first question, if you want to have an optimal filtering you need a DNS server working locally with the mentioned configuration. Regarding your VPN, you can tell it in the configuration to use the DNS server in the local address: 127.0.0.1 (that's how I have it).
Maza adds a customisation in the hosts file in case you don't use a DNS server, you can add whatever you need inside. In case you use a DNS server, you must add it in its own configuration.
I hope I have answered your questions.
Thanks for your comments.

**Comment by TommieWong** [comment]
Hi @tanrax, thanks for the replies, this is useful. I hadn't looked at the whole hosts file and have now seen the part that Maza adds. Two more questions, if you will:
- The StevenBlack repo recommends pointing all blocked domains to 0.0.0.0 instead of 127.0.0.1. Using localhost may be preferable in your setup (with local DNS), but I would rather use 0.0.0.0; how can this be changed?
- The StevenBlack blocklist has over 100,000 entries, while Maza adds around 4,000 entries. I thought Maza would pull information from StevenBlack but, as we see from the number of entries, this is not the case. Is this possible?
Thanks!
Tommie

**Comment by TommieWong** [comment]
Ahah, "it's not a good idea to point to 0.0.0.0" is quite a tease. Thanks for the help!
