### ISSUE TITLE
Safe to use other hosts file lists with maza?

### ISSUE THREAD

**Issue by gregorylearns** [tanrax/maza-ad-blocking#15]
Are there any plans to allow for easier config of maza host file? I plan to use it with Steven Black's aggregated host lists. I've gone ahead and edited `/usr/local/bin/maza`. Is there any other 'official' method of doing this?

Thanks! love your work

**Comment by tanrax** [comment]
I have modified the script and the README a bit to show you an example.
Thank you!
https://github.com/tanrax/maza-ad-blocking/blob/master/README.md#-alternative-dns-list

**Comment by gregorylearns** [comment]
It's perfect, thanks again!
