### ISSUE TITLE
Obligatory "Windows Please" Post

### ISSUE THREAD

**Issue by y0himba** [tanrax/maza-ad-blocking#18]
I would love to see this for Windows.

**Comment by tanrax** [comment]
It may work with WSL2. If you want to try it, that would be great.

**Comment by y0himba** [comment]
Thanks for the reply!

It works under WSL2. The issuse is how do I get my browsers and other programs to use it? How do I get it to start at startup with windows?  

Will Windows interact with the Linux subsystem?
![image](https://user-images.githubusercontent.com/11462603/212560380-2beed105-4332-4d09-b6b0-3a5bf236358c.png)

**Comment by tanrax** [comment]
I guess the next step is to set up a DNS server in WSL with Dnsmasq (I explain how to do it) and change the Windows DNS to point to Dnsmasq.

**Comment by tanrax** [comment]
I close it due to inactivity
