### ISSUE TITLE
dnsmasq /127.0.0.1 bad option

### ISSUE THREAD

**Issue by shivshankar3578** [tanrax/maza-ad-blocking#20]
ζ brew info dnsmasq                                                                                                                                                                             
==> dnsmasq: stable 2.89 (bottled)

Following installation steps give following error 
_dnsmasq: bad option at line 4 of /Users/shivshankarsharma/.maza/dnsmasq.conf_
I tried to comment line 4 that is **/127.0.0.1** then give me error for another line
NOTE: I'm trying with URL_DNS_LIST="https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"

**Comment by tanrax** [comment]
Share me your content of dnsmasq.conf that Maza generates.

**Comment by codingCoffee** [comment]
Facing the same issue with StevenBlack's host list

Here's the dnsmasq.conf which Maza generated: https://pastebin.com/Wu9T2DW0

**Comment by tanrax** [comment]
The file was not created correctly, it is as if it was corrupted or modified by hand. Maybe the connection was cut? I would generate it again. Here is a sample of how it should start.

```
## MAZA - List ad blocking
### https://github.com/tanrax/maza-ad-blocking
### Created by Andros Fenollosa (https://andros.dev/)
address=/1-1ads.com/127.0.0.1
address=/101com.com/127.0.0.1
address=/101order.com/127.0.0.1
address=/123freeavatars.com/127.0.0.1
address=/180hits.de/127.0.0.1
address=/1link2020.com/127.0.0.1
address=/1rx.io/127.0.0.1
address=/207.net/127.0.0.1
address=/247media.com/127.0.0.1
address=/24log.com/127.0.0.1
address=/24log.de/127.0.0.1
address=/24pm-affiliation.com/127.0.0.1
address=/2mdn.net/127.0.0.1
address=/2o7.net/127.0.0.1
address=/2znp09oa.com/127.0.0.1
address=/30ads.com/127.0.0.1
address=/3337723.com/127.0.0.1
address=/33across.com/127.0.0.1
address=/360yield.com/127.0.0.1
address=/3o9s.short.gy/127.0.0.1
address=/4d5.net/127.0.0.1
address=/4info.com/127.0.0.1
```

**Comment by tanrax** [comment]
@codingCoffee @shivshankar3578  I see the problem. StevenBlack's host list format is not supported.
The format is currently not supported. I will leave a warning note in the README. Perhaps a compatibility and status table would be needed.
Thanks for the heads up.

**Comment by StevenBlack** [comment]
👋🏻 Hello everybody and Andros @tanrax here's a suggestion: 

The lines highlighted in the image above ⬆️ are common, in whole or in part, to all hosts files.  Rules to handle this would be a small finite set.  Just 14 lines covers all OEM hosts files shipped with Windows OS (current and historical) as well as all hosts versions shipped with the various Linux OS.

Since the set if finite and bounded, I'm suggesting you could filter those lines as part of any pre-processing and validation you may be doing already.

**Comment by tanrax** [comment]
I have uploaded an update. The domains in the highlighted list will now be ignored by default. I have also added improvements to make "Steven Black's main list" or any other similar list work better. 
To make it work:
- Delete the ".config/maza/ignore" file.
- Update maza: "curl -o maza https://raw.githubusercontent.com/tanrax/maza-ad-blocking/master/maza && sudo rm -rf /usr/local/bin/maza && chmod +x maza && sudo mv maza /usr/local/bin".
- Update list: "maza update".

Happy hacking!

**Comment by sbstn87** [comment]
Is is just me, or now the Steven Black's list is enabled by default?

**Comment by tanrax** [comment]
@sbstn87 Use Yoyo by default. If you want to use Steven Black's list, see the README for instructions on how to make this possible. You only have to modify one line  😉
