### ISSUE TITLE
config directory inconcistency

### ISSUE THREAD

**Issue by codingCoffee** [tanrax/maza-ad-blocking#23]
Config directory when running `maza update` is `$HOME/.config/maza`, but while running `sudo maza start` is `$HOME/.maza`. This is owing to the availability of `XDG_CONFIG_HOME` bash variable. It resolves to `$HOME/.config` as the normal user, but when executed as root it resolves to nothing.

A potential fix is submitted in https://github.com/tanrax/maza-ad-blocking/pull/22 to standardize the config directory.

**Comment by tanrax** [comment]
Thank you for the PR.
