### ISSUE TITLE
Block prono

### ISSUE THREAD

**Issue by hajsf** [tanrax/maza-ad-blocking#24]
Hi, is there a way to block prono or nudity in any video streaming or image? Thanks.

**Comment by tanrax** [comment]
Yes! You can use an alternative list such as:
StevenBlack/hosts extension porn
http://sbc.io/hosts/alternates/porn-only/hosts

**Comment by tanrax** [comment]
Of course.
Add as many custom domains as you like. See the link below.
https://github.com/tanrax/maza-ad-blocking#-add-custom-domains-to-block
