### ISSUE TITLE
Tutorial problem with dnsmasq

### ISSUE THREAD

**Issue by alohl669** [tanrax/maza-ad-blocking#25]
There is something wrong with the tutorial.
When you start dnsmasq you could have a problem because you never create the `/home/$USER/.maza/dnsmasq.conf` file.

![image](https://github.com/tanrax/maza-ad-blocking/assets/35612640/aae2b46b-f9fe-4eca-938f-7eb62384eb20)

not even root user.

PS, for the tutorial: On debian you could have problems installing dnsmasq because systemctl-resolve uses port 53. You can resolve adding this line `DNSStubListener=no` to `/etc/systemd/resolved.conf` file

**Comment by tanrax** [comment]
Hello!
The path you are using is wrong, it is created inside `(user path)/.config/maza/dnsmasq.conf`.
Where in the tutorial is this route indicated? I can't find it.

**Comment by tanrax** [comment]
I see, it's the tutorial on how to build your own pi-hole. Thanks for the tip 😄

**Comment by alohl669** [comment]
> Hello! The path you are using is wrong, it is created inside `(user path)/.config/maza/dnsmasq.conf`. Where in the tutorial is this route indicated? I can't find it.


> I see, it's the tutorial on how to build your own pi-hole. Thanks for the tip 😄

Exactly, I'm using this [tutorial](https://programadorwebvalencia.com/create-your-own-pi-hole-with-10-commands/) because I want to test in a VPS that I have, and the tutorial indicates that we can use something like that.

By the way, Thanks for clarifying the path, just one more thing, when you use this tutorial, you use `sudo maza update` which means that you can save explanations about `user` and put directly `/root/.config/maza`

**Comment by tanrax** [comment]
You are welcome! That's right, I personally run it with root so everything is in the /root/ folder
