### ISSUE TITLE
Unable to use multiple host files

### ISSUE THREAD

**Issue by someoneignorable** [tanrax/maza-ad-blocking#26]
I want to use multiple host files but it is not possible with the program

**Comment by WIttyJudge** [comment]
If someone is interested in this feature, I recently deployed my CLI tool that is inspired by Maza and pi-hole: [adess](https://github.com/WIttyJudge/adless). It has the ability to provide multiple blocklists in config file.

**Comment by tanrax** [comment]
@WIttyJudge I added your project in the README

**Comment by WIttyJudge** [comment]
@tanrax Thank you! I appreciate it a lot
