### ISSUE TITLE
Correct way of updating block list when not using DNSMASQ

### ISSUE THREAD

**Issue by osiers000** [tanrax/maza-ad-blocking#27]
Hi, thanks a lot for the software! I'm currently using maza without dnsmasq, and it seems like the only time maza writes rules to the hosts file is at `maza start` command. So in order to properly update the block list, do I need to restart maza every time rather than just calling `maza update`?

**Comment by tanrax** [comment]
Hi @osiers000 !
Thanks for reporting the problem. The host file will now be updated when you use the update command.
Be careful that your configurations must be in the `/root/.config/maza` folder! If you don't have any, you shouldn't do anything.
Enjoy it!
