### ISSUE TITLE
update list for bg web pages

### ISSUE THREAD

**Issue by igreshev** [tanrax/maza-ad-blocking#5]
<img width="1104" alt="Screenshot 2020-03-31 at 8 44 03" src="https://user-images.githubusercontent.com/1061594/77991183-d86c8500-732b-11ea-88b7-e9f2e519997f.png">

**Comment by tanrax** [comment]
Hi, I don't quite understand what the problem is you're exposing me to. It only blocks by means of DNS addresses, you never get to touch the HTML of the browser.

**Comment by igreshev** [comment]
I mean that the ads on this site are not blocked. The ad domains are missing in the list

**Comment by tanrax** [comment]
The domains to be blocked can be reported on the next page: https://pgl.yoyo.org/as/ (It's the database that feeds Maza)
Thanks for the warning!
