### ISSUE TITLE
Lint with shellcheck

### ISSUE THREAD

**Issue by cdlm** [tanrax/maza-ad-blocking#6]
[Shellcheck](https://www.shellcheck.net) reports quite a few warnings on `maza`.
I haven't investigated to check if they're that serious, but it would be reassuring to have a minimum of those, especially for a script that's going to be run under `sudo`.

**Comment by tanrax** [comment]
Thanks for the report.
If you read the warnings carefully, they are almost all double-quote notices or an arrays notice.
If you want to make me a pull request with the format improvements I will gladly accept it.
Greetings
